### PR TITLE
fix multi monitor

### LINKED ISSUE #17: default monitor instead of active is used to get size
let window_weak = window.downgrade();
    window.connect_map_event(move |_| {
        if let Some(window) = window_weak.upgrade() {
            if let Some(surface) = window.surface() {
                let display = surface.display();
                if let Some(monitor) = display.monitor_at_surface(&surface) {
                    let geometry = monitor.geometry();
                    println!(
                        "Window is on monitor at x={}, y={}, width={}, height={}",
                        geometry.x(),
                        geometry.y(),
                        geometry.width(),
                        geometry.height()
                    );
                }
            }
        }
        gtk4::Inhibit(false)
    });

### PR DESCRIPTION
**Pull request by alexmohr**
fixes #17

### CODE REVIEW

File: src/lib/gui.rs [hunk 1]
```diff
@@ -580,13 +592,12 @@ fn sort_menu_items_by_score<T: Clone>(
...
-fn animate_window_show(config: &Config, window: ApplicationWindow) {
+fn window_show_resize(config: &Config, window: ApplicationWindow) {
     if let Some(surface) = window.surface() {
-        let display = window.display();
-
-        // todo this does not work for multi monitor systems
+        let display = surface.display();
         let monitor = display.monitor_at_surface(&surface);
         if let Some(monitor) = monitor {
+            println!("{:?}", monitor.scale_factor());
```
Comment (alexmohr) [inline src/lib/gui.rs:600]: needs to be removed
